/* SPDX-License-Identifier: GPL-2.0 */
#ifndef PAGE_FLAGS_LAYOUT_H
#define PAGE_FLAGS_LAYOUT_H

#if defined(CONFIG_SPARSEMEM) && !defined(CONFIG_SPARSEMEM_VMEMMAP)
#define SECTIONS_WIDTH		SECTIONS_SHIFT  /* SECTIONS_WIDTH = SECTIONS_SHIFT */
#else
#define SECTIONS_WIDTH		0
#endif

#define ZONES_SHIFT 2
#define ZONES_WIDTH		ZONES_SHIFT

#define NODES_WIDTH		NODES_SHIFT

/* SMAP uses LAST_CPUPID field for accumulated access count */
#define NR_PAGEFLAGS		56
#define ZONES_PGOFF		(BITS_PER_LONG - ZONES_WIDTH)
#define LAST_CPUPID_SHIFT	8
#define LAST_CPUPID_WIDTH	LAST_CPUPID_SHIFT
#define LAST_CPUPID_PGOFF	(ZONES_PGOFF - LAST_CPUPID_WIDTH)
#define LAST_CPUPID_PGSHIFT	(LAST_CPUPID_PGOFF)
#define LAST_CPUPID_MASK	((1UL << LAST_CPUPID_SHIFT) - 1)

#endif
