/* SPDX-License-Identifier: GPL-2.0 */
// Generated by scripts/atomic/gen-atomic-long.sh

#ifndef _LINUX_ATOMIC_LONG_DEPENDS_H
#define _LINUX_ATOMIC_LONG_DEPENDS_H

#include <linux/compiler.h>
#include <asm/types.h>
#include <linux/types.h>

#define atomic_long_cond_read_relaxed	atomic64_cond_read_relaxed
#define atomic_long_cond_read_acquire	atomic64_cond_read_acquire
#define ATOMIC_LONG_INIT(i)		ATOMIC64_INIT(i)
typedef atomic64_t atomic_long_t;

#endif